<?php

function specials_menu() {
    return [
        'specials' => [
            'title' => 'Cameron\'s Daily Specials',
            'page callback' => 'specials_display',
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM
        ]
    ];
}

function specials_display() {
    return '
        <ul>
            <li>Chai Latte</li>
            <li>Chocolate Bacon Cookies</li>
            <li>Salted Caramel Apple Croissant</li>
        </ul>
    ';
}