<?php

function sum_menu() {
    return [
        'sum' => [
            'title' => 'Calculate Sum',
            'page callback' => 'drupal_get_form',
            'page arguments' => [
                'sum_form'
            ],
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM
        ],
        'success' => [
            'title' => 'Success',
            'type' => MENU_CALLBACK,
            'access callback' => TRUE,
            'page callback' => 'sum_success'
        ]
    ];
}

function sum_form() {
    return [
        'left_number' => [
            '#title' => 'Left Number',
            '#type' => 'textfield',
            '#description' => t('Please enter you starting number.'),
        ],
        'right_number' => [
            '#title' => 'Right Number',
            '#type' => 'textfield',
            '#description' => t('Please enter the number to add to the starting number.'),
        ],
        'submit' => [
            '#type' => 'submit',
            '#value' => 'Calculate sum',
        ],
    ];
}

function sum_form_submit($form, &$form_state) {
    $_SESSION['sum_output'] = $form_state['values']['left_number'] + $form_state['values']['right_number'];
    $form_state['redirect'] = 'success';
}

function sum_success() {
    return 'You calculated the sum! ' . $_SESSION['sum_output'];
}